name: Sync to Gitee

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: Yikun/hub-mirror-action@v1.5
        with:
          src: github/${{ github.repository_owner }}
          dst: gitee/${{ secrets.GITEE_USERNAME }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: ${{ github.event.repository.name }}
          force_update: true
          clone_style: https
